#!/usr/bin/env bash
set -eu
exec 2>&1

# Wait for syslog-ng to start
sleep 1
while true; do
	status=$(sv check syslog-ng |grep run)
	if [[ ! -z $status ]]; then
		break
	fi
	sleep 1
done

logger -t runit "Starting PHP-FPM"

exec /usr/sbin/php-fpm7